// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMoJcqFRUNSNQy8TiYPSouPA-LVCAw0OI',
    appId: '1:280958466968:web:b049ad2d6b90ac28fd09ed',
    messagingSenderId: '280958466968',
    projectId: 'smartincidentreport',
    authDomain: 'smartincidentreport.firebaseapp.com',
    storageBucket: 'smartincidentreport.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9B4hOQ5dxw2ckiO-0iBPxUCpgLNmHdXU',
    appId: '1:280958466968:android:b0eab4f312a954ecfd09ed',
    messagingSenderId: '280958466968',
    projectId: 'smartincidentreport',
    storageBucket: 'smartincidentreport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn4yTJufILWe0z9vZJdveNff9IWxrPQSk',
    appId: '1:280958466968:ios:3aac4bae0967efd4fd09ed',
    messagingSenderId: '280958466968',
    projectId: 'smartincidentreport',
    storageBucket: 'smartincidentreport.firebasestorage.app',
    iosBundleId: 'com.example.smartIncidentRepoter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn4yTJufILWe0z9vZJdveNff9IWxrPQSk',
    appId: '1:280958466968:ios:3aac4bae0967efd4fd09ed',
    messagingSenderId: '280958466968',
    projectId: 'smartincidentreport',
    storageBucket: 'smartincidentreport.firebasestorage.app',
    iosBundleId: 'com.example.smartIncidentRepoter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMoJcqFRUNSNQy8TiYPSouPA-LVCAw0OI',
    appId: '1:280958466968:web:7875c2f23c4ff414fd09ed',
    messagingSenderId: '280958466968',
    projectId: 'smartincidentreport',
    authDomain: 'smartincidentreport.firebaseapp.com',
    storageBucket: 'smartincidentreport.firebasestorage.app',
  );
}
